site_name: zLab

plugins:
  - blog:
      post_url_date_format: yyyy/MM/dd
      blog_dir: .
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

nav:
  - index.md

theme:
  font:
    text: Serif
  name: material
  logo: assets/郭.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Header

# Footer
extra:
  generator: false
  analytics:
    provider: google
    property: G-X956BD08NG

copyright: Copyright &copy; 2023 zLab

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
