site_name: zLab

# Shows last modified and creation time for a post
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

theme:
  name: material
  logo: assets/郭.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Header

# Footer
extra:
  generator: false
  
# Footer Copyright      
copyright: Copyright &copy; 2023 zLab

    