name: Coffee Journal Entry
description: Log a new 4:6 Method brew.
title: "Brew Log"
labels: ["coffee-log"]
body:
  - type: markdown
    attributes:
      value: |
        ## The Beans
  - type: input
    id: bean_name
    attributes:
      label: Bean Name
      placeholder: e.g. Ethiopia Guji Uraga
    validations:
      required: true
  - type: dropdown
    id: roaster
    attributes:
      label: Roaster
      options:
        - Onyx
        - Sey
        - La Cabra
        - Devocion
    validations:
      required: true
  - type: dropdown
    id: roast_level
    attributes:
      label: Roast Level
      options:
        - Light
        - Medium-Light
        - Medium
        - Medium-Dark
        - Dark
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## The Recipe (4:6 Method)
  - type: input
    id: grinder
    attributes:
      label: Grinder & Setting
      placeholder: e.g. Comandante @ 24 clicks
    validations:
      required: true
  - type: input
    id: dose
    attributes:
      label: Dose (g)
      value: "20"
    validations:
      required: true
  - type: input
    id: water
    attributes:
      label: Total Water (g)
      value: "300"
    validations:
      required: true
  - type: input
    id: temp
    attributes:
      label: Water Temp (°C)
      value: "93"
    validations:
      required: true
  - type: input
    id: pour_interval
    attributes:
      label: Pour Interval (seconds)
      description: Time between each pour (standard 4:6 method uses 45s)
      value: "45"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Phase 1: Balance (First 40%)
        Total for this phase is usually 40% of Total Water (e.g., 120g for 300g total).
  - type: input
    id: first_pour
    attributes:
      label: First Pour Amount (g)
      description: Less than half = SWEETER. More than half = ACIDIC.
      placeholder: "50"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Phase 2: Strength (Last 60%)
        How many pours did you split the last 60% into?
  - type: dropdown
    id: strength_pours
    attributes:
      label: Strength Pours
      options:
        - 1 Pour (Light)
        - 2 Pours (Medium)
        - 3 Pours (Strong)
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## SCA Sensory Evaluation (1-10 scale, max 90 points)
  - type: dropdown
    id: aroma
    attributes:
      label: Aroma (香气)
      description: Dry and wet fragrance; first impression of potential flavor and complexity
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: flavor
    attributes:
      label: Flavor (风味)
      description: Primary taste characteristics; combined impression of taste and retronasal aroma
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: aftertaste
    attributes:
      label: Aftertaste (余韵)
      description: Length and pleasantness of flavor after swallowing; positive finish should be clean and sweet
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: acidity
    attributes:
      label: Acidity (酸质)
      description: Liveliness or brightness; high-quality acidity should be crisp and sweet
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: body
    attributes:
      label: Body (醇厚度)
      description: Physical mouthfeel and weight (e.g., light or syrupy)
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: balance
    attributes:
      label: Balance (平衡度)
      description: Harmony among flavor, aftertaste, acidity, and body
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: clean_cup
    attributes:
      label: Clean Cup (干净度)
      description: Free from interfering negative flavors or defects from start to finish
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: sweetness
    attributes:
      label: Sweetness (甜度)
      description: Natural sweetness and pleasant fullness
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: dropdown
    id: overall
    attributes:
      label: Overall (总体评价)
      description: Personal, comprehensive evaluation of overall quality and value
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 5
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Tasting Notes
      placeholder: Jasmine, Bergamot, slight astringency at the end...
